/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mx.itson.cinemovie.presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import mx.itson.cinemovie.entidades.Pelicula;
/**
 * Interfaz con la lista de peliculas
 * @author Michelle
 * @author Emmanuel
 */
public class PeliculasLista extends javax.swing.JFrame {

    /**
     * Creates new form ListaPeliculas
     */
    
    // Modelo para almacenar la tabla pelicula
    DefaultTableModel modelo;
    
    public PeliculasLista() {
        initComponents();
        // Tabla pelicula convertida a modelo
        modelo = (DefaultTableModel)tblPeliculas.getModel();
        // Cambiar la longitud de ciertas columnas
        tblPeliculas.getColumnModel().getColumn(0).setPreferredWidth(5);
        tblPeliculas.getColumnModel().getColumn(2).setPreferredWidth(5);
        tblPeliculas.getColumnModel().getColumn(4).setPreferredWidth(5);
        // Desactivar los botones de editar y eliminar pelicula
        btnEditarPeli.setEnabled(false);
        btnEliminarPeli.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPeliculas = new javax.swing.JTable();
        btnAgregarPeli = new javax.swing.JButton();
        btnEditarPeli = new javax.swing.JButton();
        btnEliminarPeli = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tblPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Titulo", "Duracion", "Genero", "Calificacion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPeliculas);

        btnAgregarPeli.setBackground(new java.awt.Color(153, 255, 102));
        btnAgregarPeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAgregarPeli.setForeground(new java.awt.Color(102, 153, 0));
        btnAgregarPeli.setText("Agregar Pelicula");
        btnAgregarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarPeliActionPerformed(evt);
            }
        });

        btnEditarPeli.setBackground(new java.awt.Color(153, 153, 255));
        btnEditarPeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEditarPeli.setForeground(new java.awt.Color(102, 0, 204));
        btnEditarPeli.setText("Editar Pelicula");
        btnEditarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarPeliActionPerformed(evt);
            }
        });

        btnEliminarPeli.setBackground(new java.awt.Color(255, 153, 153));
        btnEliminarPeli.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnEliminarPeli.setForeground(new java.awt.Color(153, 0, 51));
        btnEliminarPeli.setText("Eliminar Pelicula");
        btnEliminarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPeliActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 0, 153));
        jLabel2.setText("Peliculas");

        btnRegresar.setBackground(new java.awt.Color(153, 153, 255));
        btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 0, 204));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnRegresar)
                .addGap(225, 225, 225)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(btnRegresar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 26, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAgregarPeli)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditarPeli)
                .addGap(178, 178, 178)
                .addComponent(btnEliminarPeli)
                .addGap(37, 37, 37))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarPeli)
                    .addComponent(btnEditarPeli)
                    .addComponent(btnEliminarPeli, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metodo para cargar la tabla peliculas de la base de datos e importarla al programa
     */
    /*private void cargarTabla(){

       DefaultTableModel modelo = (DefaultTableModel)tblPeliculas.getModel();
       modelo.setRowCount(0);
       
       // Por cada pelicula que exista en peliculas se agregara la misma a la tabla
       for(Pelicula p : peliculas){
           modelo.addRow(new Object[] {
               p.getId(),
               p.getTitulo(),
               p.getDuracion(),
               p.getGenero(),
           });
       }
    }*/
    
    private void btnAgregarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarPeliActionPerformed
        // TODO add your handling code here:
        PeliculasForm peliculasForm = new PeliculasForm(this, true);
        peliculasForm.setVisible(true);
        
        btnEliminarPeli.setEnabled(false);
        btnEditarPeli.setEnabled(false);
        Pelicula.cargarTabla(modelo);
    }//GEN-LAST:event_btnAgregarPeliActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Pelicula.cargarTabla(modelo);
    }//GEN-LAST:event_formWindowOpened

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // Regresa al Jframe principal
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnEditarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPeliActionPerformed
        // Guarda los valores de la fila seleccionada
        int id = Integer.parseInt(tblPeliculas.getValueAt(tblPeliculas.getSelectedRow(), 0).toString());
        String titulo = tblPeliculas.getValueAt(tblPeliculas.getSelectedRow(), 1).toString();
        Double duracion = Double.parseDouble(tblPeliculas.getValueAt(tblPeliculas.getSelectedRow(), 2).toString());
        String genero = tblPeliculas.getValueAt(tblPeliculas.getSelectedRow(), 3).toString();
        
        PeliculasForm peliculasForm = new PeliculasForm(this, true);
        // Escribe los valores anteriormente seleccionados en los campos del formulario peliculas
        peliculasForm.setId(id);
        peliculasForm.setTitulo(titulo);
        peliculasForm.setDuracion("" + duracion);
        peliculasForm.setGenero(genero);
        peliculasForm.setVisible(true);
        
        btnEliminarPeli.setEnabled(false);
        btnEditarPeli.setEnabled(false);
        Pelicula.cargarTabla(modelo);
    }//GEN-LAST:event_btnEditarPeliActionPerformed

    private void btnEliminarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPeliActionPerformed

        // Crea una variable que almacenara la id de cada columna seleccionada
        int ids[] = tblPeliculas.getSelectedRows();
        // Asigna la id correspondiente a las peliculas a cada campo que existe en ids
        for (int i=0; tblPeliculas.getSelectedRowCount()>i; i++){
            ids[i] = Integer.parseInt(tblPeliculas.getValueAt(tblPeliculas.getSelectedRows()[i], 0).toString());
        }
        boolean resultado = Pelicula.eliminar(ids);
        
        // Mostrar un mensaje de dialogo dependiendo del valor de resultado
        if(resultado){
            JOptionPane.showMessageDialog(this, "El registro se actualizo correctamente", "Registro borrado", JOptionPane.INFORMATION_MESSAGE);
            btnEliminarPeli.setEnabled(false);
            btnEditarPeli.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error al borrar", "Error", JOptionPane.ERROR_MESSAGE);
        }
        Pelicula.cargarTabla(modelo);
    }//GEN-LAST:event_btnEliminarPeliActionPerformed

    private void tblPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPeliculasMouseClicked
        // Mientras solo sea seleccionada una fila, activar el boton de editar pelicula
        if (tblPeliculas.getSelectedRows().length == 1){
            btnEditarPeli.setEnabled(true);
        } else {
            btnEditarPeli.setEnabled(false);
        }
        
        // Si no esta seleccionada ninguna fila, desactivar los botones, de lo contrario, activar el boton de eliminar pelicula
        if (tblPeliculas.getSelectedRows().length != 0){
            btnEliminarPeli.setEnabled(true);
        } else {
            btnEliminarPeli.setEnabled(false);
            btnEditarPeli.setEnabled(false);
        }
    }//GEN-LAST:event_tblPeliculasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PeliculasLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PeliculasLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PeliculasLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PeliculasLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PeliculasLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarPeli;
    private javax.swing.JButton btnEditarPeli;
    private javax.swing.JButton btnEliminarPeli;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPeliculas;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTable getTblPeliculas(){
        return tblPeliculas;
    }
}
